NIFTY500_SYMBOLS = [
    "RELIANCE.NS","TCS.NS","INFY.NS","HDFCBANK.NS","ICICIBANK.NS","SBIN.NS","HINDUNILVR.NS","KOTAKBANK.NS","LT.NS","BHARTIARTL.NS",
    "AXISBANK.NS","ITC.NS","ASIANPAINT.NS","BAJFINANCE.NS","MARUTI.NS","SUNPHARMA.NS","NTPC.NS","NESTLEIND.NS","POWERGRID.NS","ONGC.NS",
    "TITAN.NS","ULTRACEMCO.NS","BAJAJFINSV.NS","HCLTECH.NS","WIPRO.NS","TECHM.NS","JSWSTEEL.NS","TATASTEEL.NS","ADANIGREEN.NS","ADANIPORTS.NS",
    "ADANIENT.NS","BRITANNIA.NS","GRASIM.NS","CIPLA.NS","HDFCLIFE.NS","DRREDDY.NS","DIVISLAB.NS","SBILIFE.NS","ICICIPRULI.NS","EICHERMOT.NS",
    "M&M.NS","BAJAJ-AUTO.NS","HEROMOTOCO.NS","APOLLOHOSP.NS","INDUSINDBK.NS","BPCL.NS","IOC.NS","COALINDIA.NS","VEDL.NS","DMART.NS",
    # ... continue adding all you want
]
